image: dcr.danawa.io/alpine-k8s-golang:1.16.5

cache:
  key: cache1
  paths:
    - /root/go/pkg/mod

variables:
  GOPATH: /root/go/pkg/mod

build:
  stage: build
  script:
    - git clone -b master --single-branch https://github.com/danawalab/es-extention-api.git
    - cd es-extention-api
    - rm -rf dist
    - go build -o dist/application cmd/es-extention-api/main.go
    - export port=9000
    - export es_urls=http://elasticsearch:9200
    - export go_env=production
    - |
      cat <<EOF > Dockerfile
      FROM golang:1.16.5
      COPY dist/application application
      RUN echo date > build.txt
      CMD ./application port=\$port es.urls=\$es_urls go.env=\$go_env
      EOF
    - docker build -t ${REGISTRY}/${IMAGE}:latest .
    - docker push ${REGISTRY}/${IMAGE}:latest

Elk2-Dev Deploy:
  stage: deploy
  script:
    - echo curl -H "x-auth-token=${ELK2_DEV_TOKEN}" -XPUT ${ELK2_DEV_URL}
    - curl -H "x-auth-token=${ELK2_DEV_TOKEN}" -XPUT ${ELK2_DEV_URL}

