###################################################################################
#
#   2021.12.28 김준우
#
#   ** 실제 CI/CD 사용하기 전 체크 항목 **
#   1. Golang Project인지 확인
#   2. REGISTRY_IMAGE 뒤에 `-flow`는 제거
#   3. DOCKER_FILE 파일명, ARG == --build-arg 명령어 체크
#   4. 테스트 배포 확인 후 사용
#   5. secrets CR_TOKEN 유효, 저장소 선택 확인
#
##################################################################################
 
name: docker-release-ci
 
on:
  push:
    branches: [ release/**, hotfix/** ]
  pull_request:
    branches: [ release/**, hotfix/** ]
 
env:
  CONTAINER_REGISTRY: ghcr.io
  DOCKER_FILE: Dockerfile.flow
  TAG_SUFFIX: -rc
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     소스 체크아웃
    - uses: actions/checkout@v2
     
#     저장소이름 추출
    - name: PROJECT_NAME Exctract
      run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY|cut -d '/' -f 2)" >> $GITHUB_ENV
 
#     브랜치 추출
    - name: BRANCH_VERSION Exctract
      run: echo "BRANCH_VERSION=$(echo $GITHUB_REF_NAME|cut -d '/' -f 2)$TAG_SUFFIX" >> $GITHUB_ENV
 
#     GO 활성화
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

#     고 빌드
    - name: build
      run: go build -o dist/application cmd/es-extention-api/main.go

#     퍼미션 변경    
    - name: permission
      run: chmod 755 dist/application

#     도커 로그인
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
#         danawalab 계정에선 토큰이 안보임..
        username: joonwoo8888
        password: ${{ secrets.CR_TOKEN }}
 
#     도커 빌드/푸시
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        dockerfile: ${{ env.DOCKER_FILE }}
        image: ${{ env.PROJECT_NAME }}
        tags: ${{ env.BRANCH_VERSION }}
     
